name: Build and Deploy to Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
        id: pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Adjust if your HTML/CSS files are in a subdirectory

      - uses: actions/deploy-pages@v1
        id: deployment
